(FOOTPAD DIAL SHAFT BEARING-ROTAT SPRING LEVER2NDCLASS CYLINDER TORSION-SPRING CYLINDER
  LEVER1STCLASS POTENTIOMETER TORSION-SPRING POTENTIOMETER)) 
((#S(FP :THROUGH (NIL NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS ((0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0))
        :CLASS POWER :DOMAIN ELECT :COORD NIL :INTER WIRE :DIRECT SINK
        :INDEX ((13 0) GROUND))
  #S(FP :THROUGH (NIL NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS (NIL NIL NIL (0 0 0) NIL NIL NIL NIL) :CLASS NIL :DOMAIN ROTAT :COORD NIL
        :INTER SHAFT-SURFACE :DIRECT SINK :INDEX ((13 2)))
  #S(FP :THROUGH (NIL NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS (NIL NIL NIL NIL NIL NIL (0 0 0) NIL) :CLASS NIL :DOMAIN ELECT :COORD NIL
        :INTER WIRE :DIRECT SINK :INDEX ((13 1) (12 0)))
  #S(FP :THROUGH (NIL NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS (NIL NIL NIL NIL NIL NIL (0 0 0) NIL) :CLASS NIL :DOMAIN ELECT :COORD NIL
        :INTER WIRE :DIRECT SINK :INDEX ((12 1)))
  #S(FP :THROUGH ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) NIL (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        (((GOAL 0) (GOAL 0) BOUND) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         (0 0 0) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN TRANS :COORD NIL :INTER BOLT :DIRECT SINK
        :INDEX ((12 2) (9 0) (8 1) (7 1) (6 1) (5 1)))
  #S(FP :THROUGH ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) NIL (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        (((GOAL 0) (GOAL 0) BOUND) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         (0 0 0) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN ROTAT :COORD NIL :INTER BOLT :DIRECT SINK
        :INDEX ((11 1) (10 2) (9 1)))
  #S(FP :THROUGH ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) NIL (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        (((GOAL 0) (GOAL 0) BOUND) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         (0 0 0) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN ROTAT :COORD NIL :INTER BOLT :DIRECT SINK
        :INDEX ((11 0) (7 0) (5 0) (4 1) (3 1)))
  #S(FP :THROUGH (NIL NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS ((0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0))
        :CLASS POWER :DOMAIN ELECT :COORD NIL :INTER WIRE :DIRECT SINK
        :INDEX ((10 0) GROUND))
  #S(FP :THROUGH (NIL NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS (NIL NIL NIL NIL NIL NIL (0 0 0) NIL) :CLASS NIL :DOMAIN ELECT :COORD NIL
        :INTER WIRE :DIRECT SINK :INDEX ((10 1)))
  #S(FP :THROUGH ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) NIL (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        ((NIL (GOAL BOUND) NIL) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         (0 0 0) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN HYDRA :COORD NIL :INTER PIPE :DIRECT SINK :INDEX ((6 0)))
  #S(FP :THROUGH ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) NIL (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        ((NIL (GOAL BOUND) NIL) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         (0 0 0) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN HYDRA :COORD NIL :INTER PIPE :DIRECT SINK :INDEX ((8 0)))
  #S(FP :THROUGH ((GOAL BOUND) NIL NIL NIL NIL NIL NIL NIL)
        :ACROSS ((0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0))
        :CLASS POWER :DOMAIN TRANS :COORD NIL :INTER BOLT :DIRECT SINK :INDEX ((4 0) GROUND))
  #S(FP :THROUGH
        ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) (GOAL BOUND) (GOAL 0) (GOAL 0) (GOAL 0)
         (GOAL 0))
        :ACROSS
        (((GOAL 0) (GOAL 0) BOUND) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL NIL) (GOAL NIL) (GOAL (0 5))) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL 0) (GOAL 0) (GOAL 0)))
        :CLASS POWER :DOMAIN ROTAT :COORD ((-1 0 0 1) (0 1 0 5) (0 0 -1 0) (0 0 0 1))
        :INTER NIL :DIRECT SINK :INDEX ((1 1) (GOAL 1)))
  #S(FP :THROUGH
        ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) (GOAL BOUND) (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        (((GOAL 0) (GOAL 0) BOUND) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL NIL) (GOAL NIL) (GOAL (0 5))) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN ROTAT :COORD NIL :INTER NIL :DIRECT SINK :INDEX ((2 0) (1 0)))
  #S(FP :THROUGH
        ((GOAL BOUND) (GOAL BOUND) (GOAL BOUND) (GOAL BOUND) (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS
        (((GOAL 0) (GOAL 0) BOUND) ((GOAL 0) (GOAL 0) (GOAL 0)) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL NIL) (GOAL NIL) (GOAL (0 5))) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL 0) (GOAL 0) (GOAL 0)) NIL NIL)
        :CLASS NIL :DOMAIN ROTAT :COORD NIL :INTER NIL :DIRECT SINK :INDEX ((3 0) (2 1)))
  #S(FP :THROUGH ((0 300) (GOAL 0) (GOAL 0) (GOAL 0) (GOAL 0) (GOAL 0) (GOAL 0) (GOAL 0))
        :ACROSS
        ((0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) ((GOAL 0) (GOAL 0) (GOAL 0))
         ((GOAL 0) (GOAL 0) (GOAL 0)))
        :CLASS POWER :DOMAIN TRANS :COORD ((0 1 0 0) (-1 0 0 0) (0 0 1 0) (0 0 0 1))
        :INTER NIL :DIRECT SOURCE :INDEX ((0 0) (GOAL 0)))
  #S(FP :THROUGH ((0 300) (GOAL 0) (GOAL 0) (GOAL 0) (GOAL 0) (GOAL 0) NIL NIL)
        :ACROSS ((0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0) (0 0 0))
        :CLASS POWER :DOMAIN TRANS :COORD NIL :INTER BOLT :DIRECT SINK
        :INDEX ((0 1) GROUND)))
 (FOOTPAD DIAL SHAFT BEARING-ROTAT SPRING LEVER2NDCLASS CYLINDER TORSION-SPRING CYLINDER
  LEVER1STCLASS POTENTIOMETER TORSION-SPRING POTENTIOMETER GENERATOR)) 
Error: Stack overflow (signal 1000)
[condition type: SYNCHRONOUS-OPERATING-SYSTEM-SIGNAL]
