(
;;; CONFIGURATION-AGENTS	
;;; Agents are named based on how they derive solutions.
;;; For example, in this first agent, agent-bfs-mg-forward
;;; the agent chooses to work from a source fp and then preforming a 
;;; breadth-first-search starting first with the operator (deriv, none, integ)
;;; and then finally based on choosing which component from that set at random.
 (((agent-trans-source-series-connect (0.2 0.2 0.2 0.2 -0.2) trans source series connect))
  ((agent-trans-source-series-connect (0.6 0.1 0.1 0.1 -0.1) trans source series connect))
  ((agent-trans-source-series-connect (0.1 0.6 0.1 0.1 -0.1) trans source series connect))
  ((agent-trans-source-series-connect (0.1 0.1 0.6 0.1 -0.1) trans source series connect))
  ((agent-rotat-source-series-connect (0.2 0.2 0.2 0.2 -0.2) rotat source series connect))
  ((agent-rotat-source-series-connect (0.6 0.1 0.1 0.1 -0.1) rotat source series connect))
  ((agent-rotat-source-series-connect (0.1 0.6 0.1 0.1 -0.1) rotat source series connect))
  ((agent-rotat-source-series-connect (0.1 0.1 0.6 0.1 -0.1) rotat source series connect))
  ((agent-elect-source-series-connect (0.2 0.2 0.2 0.2 -0.2) elect source series connect))
  ((agent-elect-source-series-connect (0.6 0.1 0.1 0.1 -0.1) elect source series connect))
  ((agent-elect-source-series-connect (0.1 0.6 0.1 0.1 -0.1) elect source series connect))
  ((agent-elect-source-series-connect (0.1 0.1 0.6 0.1 -0.1) elect source series connect))
  ((agent-hydra-source-series-connect (0.2 0.2 0.2 0.2 -0.2) hydra source series connect))
  ((agent-hydra-source-series-connect (0.6 0.1 0.1 0.1 -0.1) hydra source series connect))
  ((agent-hydra-source-series-connect (0.1 0.6 0.1 0.1 -0.1) hydra source series connect))
  ((agent-hydra-source-series-connect (0.1 0.1 0.6 0.1 -0.1) hydra source series connect))
  ((agent-trans-sink-series-connect (0.2 0.2 0.2 0.2 -0.2) trans sink series connect))
  ((agent-trans-sink-series-connect (0.6 0.1 0.1 0.1 -0.1) trans sink series connect))
  ((agent-trans-sink-series-connect (0.1 0.6 0.1 0.1 -0.1) trans sink series connect))
  ((agent-trans-sink-series-connect (0.1 0.1 0.6 0.1 -0.1) trans sink series connect))
  ((agent-rotat-sink-series-connect (0.2 0.2 0.2 0.2 -0.2) rotat sink series connect))
  ((agent-rotat-sink-series-connect (0.6 0.1 0.1 0.1 -0.1) rotat sink series connect))
  ((agent-rotat-sink-series-connect (0.1 0.6 0.1 0.1 -0.1) rotat sink series connect))
  ((agent-rotat-sink-series-connect (0.1 0.1 0.6 0.1 -0.1) rotat sink series connect))
  ((agent-elect-sink-series-connect (0.2 0.2 0.2 0.2 -0.2) elect sink series connect))
  ((agent-elect-sink-series-connect (0.6 0.1 0.1 0.1 -0.1) elect sink series connect))
  ((agent-elect-sink-series-connect (0.1 0.6 0.1 0.1 -0.1) elect sink series connect))
  ((agent-elect-sink-series-connect (0.1 0.1 0.6 0.1 -0.1) elect sink series connect))
  ((agent-hydra-sink-series-connect (0.2 0.2 0.2 0.2 -0.2) hydra sink series connect))
  ((agent-hydra-sink-series-connect (0.6 0.1 0.1 0.1 -0.1) hydra sink series connect))
  ((agent-hydra-sink-series-connect (0.1 0.6 0.1 0.1 -0.1) hydra sink series connect))
  ((agent-hydra-sink-series-connect (0.1 0.1 0.6 0.1 -0.1) hydra sink series connect))
  ((agent-trans-source-parallel-connect (0.2 0.2 0.2 0.2 -0.2) trans source parallel connect))
  ((agent-trans-source-parallel-connect (0.6 0.1 0.1 0.1 -0.1) trans source parallel connect))
  ((agent-trans-source-parallel-connect (0.1 0.6 0.1 0.1 -0.1) trans source parallel connect))
  ((agent-trans-source-parallel-connect (0.1 0.1 0.6 0.1 -0.1) trans source parallel connect))
  ((agent-rotat-source-parallel-connect (0.2 0.2 0.2 0.2 -0.2) rotat source parallel connect))
  ((agent-rotat-source-parallel-connect (0.6 0.1 0.1 0.1 -0.1) rotat source parallel connect))
  ((agent-rotat-source-parallel-connect (0.1 0.6 0.1 0.1 -0.1) rotat source parallel connect))
  ((agent-rotat-source-parallel-connect (0.1 0.1 0.6 0.1 -0.1) rotat source parallel connect))
  ((agent-elect-source-parallel-connect (0.2 0.2 0.2 0.2 -0.2) elect source parallel connect))
  ((agent-elect-source-parallel-connect (0.6 0.1 0.1 0.1 -0.1) elect source parallel connect))
  ((agent-elect-source-parallel-connect (0.1 0.6 0.1 0.1 -0.1) elect source parallel connect))
  ((agent-elect-source-parallel-connect (0.1 0.1 0.6 0.1 -0.1) elect source parallel connect))
  ((agent-hydra-source-parallel-connect (0.2 0.2 0.2 0.2 -0.2) hydra source parallel connect))
  ((agent-hydra-source-parallel-connect (0.6 0.1 0.1 0.1 -0.1) hydra source parallel connect))
  ((agent-hydra-source-parallel-connect (0.1 0.6 0.1 0.1 -0.1) hydra source parallel connect))
  ((agent-hydra-source-parallel-connect (0.1 0.1 0.6 0.1 -0.1) hydra source parallel connect))
  ((agent-trans-sink-parallel-connect (0.2 0.2 0.2 0.2 -0.2) trans sink parallel connect))
  ((agent-trans-sink-parallel-connect (0.6 0.1 0.1 0.1 -0.1) trans sink parallel connect))
  ((agent-trans-sink-parallel-connect (0.1 0.6 0.1 0.1 -0.1) trans sink parallel connect))
  ((agent-trans-sink-parallel-connect (0.1 0.1 0.6 0.1 -0.1) trans sink parallel connect))
  ((agent-rotat-sink-parallel-connect (0.2 0.2 0.2 0.2 -0.2) rotat sink parallel connect))
  ((agent-rotat-sink-parallel-connect (0.6 0.1 0.1 0.1 -0.1) rotat sink parallel connect))
  ((agent-rotat-sink-parallel-connect (0.1 0.6 0.1 0.1 -0.1) rotat sink parallel connect))
  ((agent-rotat-sink-parallel-connect (0.1 0.1 0.6 0.1 -0.1) rotat sink parallel connect))
  ((agent-elect-sink-parallel-connect (0.2 0.2 0.2 0.2 -0.2) elect sink parallel connect))
  ((agent-elect-sink-parallel-connect (0.6 0.1 0.1 0.1 -0.1) elect sink parallel connect))
  ((agent-elect-sink-parallel-connect (0.1 0.6 0.1 0.1 -0.1) elect sink parallel connect))
  ((agent-elect-sink-parallel-connect (0.1 0.1 0.6 0.1 -0.1) elect sink parallel connect))
  ((agent-hydra-sink-parallel-connect (0.2 0.2 0.2 0.2 -0.2) hydra sink parallel connect))
  ((agent-hydra-sink-parallel-connect (0.6 0.1 0.1 0.1 -0.1) hydra sink parallel connect))
  ((agent-hydra-sink-parallel-connect (0.1 0.6 0.1 0.1 -0.1) hydra sink parallel connect))
  ((agent-hydra-sink-parallel-connect (0.1 0.1 0.6 0.1 -0.1) hydra sink parallel connect))
  ((agent-trans-source-series-ground (0.2 0.2 0.2 0.2 -0.2) trans source series ground))
  ((agent-trans-source-series-ground (0.6 0.1 0.1 0.1 -0.1) trans source series ground))
  ((agent-trans-source-series-ground (0.1 0.6 0.1 0.1 -0.1) trans source series ground))
  ((agent-trans-source-series-ground (0.1 0.1 0.6 0.1 -0.1) trans source series ground))
  ((agent-rotat-source-series-ground (0.2 0.2 0.2 0.2 -0.2) rotat source series ground))
  ((agent-rotat-source-series-ground (0.6 0.1 0.1 0.1 -0.1) rotat source series ground))
  ((agent-rotat-source-series-ground (0.1 0.6 0.1 0.1 -0.1) rotat source series ground))
  ((agent-rotat-source-series-ground (0.1 0.1 0.6 0.1 -0.1) rotat source series ground))
  ((agent-elect-source-series-ground (0.2 0.2 0.2 0.2 -0.2) elect source series ground))
  ((agent-elect-source-series-ground (0.6 0.1 0.1 0.1 -0.1) elect source series ground))
  ((agent-elect-source-series-ground (0.1 0.6 0.1 0.1 -0.1) elect source series ground))
  ((agent-elect-source-series-ground (0.1 0.1 0.6 0.1 -0.1) elect source series ground))
  ((agent-hydra-source-series-ground (0.2 0.2 0.2 0.2 -0.2) hydra source series ground))
  ((agent-hydra-source-series-ground (0.6 0.1 0.1 0.1 -0.1) hydra source series ground))
  ((agent-hydra-source-series-ground (0.1 0.6 0.1 0.1 -0.1) hydra source series ground))
  ((agent-hydra-source-series-ground (0.1 0.1 0.6 0.1 -0.1) hydra source series ground))
  ((agent-trans-sink-series-ground (0.2 0.2 0.2 0.2 -0.2) trans sink series ground))
  ((agent-trans-sink-series-ground (0.6 0.1 0.1 0.1 -0.1) trans sink series ground))
  ((agent-trans-sink-series-ground (0.1 0.6 0.1 0.1 -0.1) trans sink series ground))
  ((agent-trans-sink-series-ground (0.1 0.1 0.6 0.1 -0.1) trans sink series ground))
  ((agent-rotat-sink-series-ground (0.2 0.2 0.2 0.2 -0.2) rotat sink series ground))
  ((agent-rotat-sink-series-ground (0.6 0.1 0.1 0.1 -0.1) rotat sink series ground))
  ((agent-rotat-sink-series-ground (0.1 0.6 0.1 0.1 -0.1) rotat sink series ground))
  ((agent-rotat-sink-series-ground (0.1 0.1 0.6 0.1 -0.1) rotat sink series ground))
  ((agent-elect-sink-series-ground (0.2 0.2 0.2 0.2 -0.2) elect sink series ground))
  ((agent-elect-sink-series-ground (0.6 0.1 0.1 0.1 -0.1) elect sink series ground))
  ((agent-elect-sink-series-ground (0.1 0.6 0.1 0.1 -0.1) elect sink series ground))
  ((agent-elect-sink-series-ground (0.1 0.1 0.6 0.1 -0.1) elect sink series ground))
  ((agent-hydra-sink-series-ground (0.2 0.2 0.2 0.2 -0.2) hydra sink series ground))
  ((agent-hydra-sink-series-ground (0.6 0.1 0.1 0.1 -0.1) hydra sink series ground))
  ((agent-hydra-sink-series-ground (0.1 0.6 0.1 0.1 -0.1) hydra sink series ground))
  ((agent-hydra-sink-series-ground (0.1 0.1 0.6 0.1 -0.1) hydra sink series ground))
  ((agent-trans-source-parallel-ground (0.2 0.2 0.2 0.2 -0.2) trans source parallel ground))
  ((agent-trans-source-parallel-ground (0.6 0.1 0.1 0.1 -0.1) trans source parallel ground))
  ((agent-trans-source-parallel-ground (0.1 0.6 0.1 0.1 -0.1) trans source parallel ground))
  ((agent-trans-source-parallel-ground (0.1 0.1 0.6 0.1 -0.1) trans source parallel ground))
  ((agent-rotat-source-parallel-ground (0.2 0.2 0.2 0.2 -0.2) rotat source parallel ground))
  ((agent-rotat-source-parallel-ground (0.6 0.1 0.1 0.1 -0.1) rotat source parallel ground))
  ((agent-rotat-source-parallel-ground (0.1 0.6 0.1 0.1 -0.1) rotat source parallel ground))
  ((agent-rotat-source-parallel-ground (0.1 0.1 0.6 0.1 -0.1) rotat source parallel ground))
  ((agent-elect-source-parallel-ground (0.2 0.2 0.2 0.2 -0.2) elect source parallel ground))
  ((agent-elect-source-parallel-ground (0.6 0.1 0.1 0.1 -0.1) elect source parallel ground))
  ((agent-elect-source-parallel-ground (0.1 0.6 0.1 0.1 -0.1) elect source parallel ground))
  ((agent-elect-source-parallel-ground (0.1 0.1 0.6 0.1 -0.1) elect source parallel ground))
  ((agent-hydra-source-parallel-ground (0.2 0.2 0.2 0.2 -0.2) hydra source parallel ground))
  ((agent-hydra-source-parallel-ground (0.6 0.1 0.1 0.1 -0.1) hydra source parallel ground))
  ((agent-hydra-source-parallel-ground (0.1 0.6 0.1 0.1 -0.1) hydra source parallel ground))
  ((agent-hydra-source-parallel-ground (0.1 0.1 0.6 0.1 -0.1) hydra source parallel ground))
  ((agent-trans-sink-parallel-ground (0.2 0.2 0.2 0.2 -0.2) trans sink parallel ground))
  ((agent-trans-sink-parallel-ground (0.6 0.1 0.1 0.1 -0.1) trans sink parallel ground))
  ((agent-trans-sink-parallel-ground (0.1 0.6 0.1 0.1 -0.1) trans sink parallel ground))
  ((agent-trans-sink-parallel-ground (0.1 0.1 0.6 0.1 -0.1) trans sink parallel ground))
  ((agent-rotat-sink-parallel-ground (0.2 0.2 0.2 0.2 -0.2) rotat sink parallel ground))
  ((agent-rotat-sink-parallel-ground (0.6 0.1 0.1 0.1 -0.1) rotat sink parallel ground))
  ((agent-rotat-sink-parallel-ground (0.1 0.6 0.1 0.1 -0.1) rotat sink parallel ground))
  ((agent-rotat-sink-parallel-ground (0.1 0.1 0.6 0.1 -0.1) rotat sink parallel ground))
  ((agent-elect-sink-parallel-ground (0.2 0.2 0.2 0.2 -0.2) elect sink parallel ground))
  ((agent-elect-sink-parallel-ground (0.6 0.1 0.1 0.1 -0.1) elect sink parallel ground))
  ((agent-elect-sink-parallel-ground (0.1 0.6 0.1 0.1 -0.1) elect sink parallel ground))
  ((agent-elect-sink-parallel-ground (0.1 0.1 0.6 0.1 -0.1) elect sink parallel ground))
  ((agent-hydra-sink-parallel-ground (0.2 0.2 0.2 0.2 -0.2) hydra sink parallel ground))
  ((agent-hydra-sink-parallel-ground (0.6 0.1 0.1 0.1 -0.1) hydra sink parallel ground))
  ((agent-hydra-sink-parallel-ground (0.1 0.6 0.1 0.1 -0.1) hydra sink parallel ground))
  ((agent-hydra-sink-parallel-ground (0.1 0.1 0.6 0.1 -0.1) hydra sink parallel ground))
  ((agent-trans-source-series-dangle (0.2 0.2 0.2 0.2 -0.2) trans source series dangle))
  ((agent-trans-source-series-dangle (0.6 0.1 0.1 0.1 -0.1) trans source series dangle))
  ((agent-trans-source-series-dangle (0.1 0.6 0.1 0.1 -0.1) trans source series dangle))
  ((agent-trans-source-series-dangle (0.1 0.1 0.6 0.1 -0.1) trans source series dangle))
  ((agent-rotat-source-series-dangle (0.2 0.2 0.2 0.2 -0.2) rotat source series dangle))
  ((agent-rotat-source-series-dangle (0.6 0.1 0.1 0.1 -0.1) rotat source series dangle))
  ((agent-rotat-source-series-dangle (0.1 0.6 0.1 0.1 -0.1) rotat source series dangle))
  ((agent-rotat-source-series-dangle (0.1 0.1 0.6 0.1 -0.1) rotat source series dangle))
  ((agent-elect-source-series-dangle (0.2 0.2 0.2 0.2 -0.2) elect source series dangle))
  ((agent-elect-source-series-dangle (0.6 0.1 0.1 0.1 -0.1) elect source series dangle))
  ((agent-elect-source-series-dangle (0.1 0.6 0.1 0.1 -0.1) elect source series dangle))
  ((agent-elect-source-series-dangle (0.1 0.1 0.6 0.1 -0.1) elect source series dangle))
  ((agent-hydra-source-series-dangle (0.2 0.2 0.2 0.2 -0.2) hydra source series dangle))
  ((agent-hydra-source-series-dangle (0.6 0.1 0.1 0.1 -0.1) hydra source series dangle))
  ((agent-hydra-source-series-dangle (0.1 0.6 0.1 0.1 -0.1) hydra source series dangle))
  ((agent-hydra-source-series-dangle (0.1 0.1 0.6 0.1 -0.1) hydra source series dangle))
  ((agent-trans-sink-series-dangle (0.2 0.2 0.2 0.2 -0.2) trans sink series dangle))
  ((agent-trans-sink-series-dangle (0.6 0.1 0.1 0.1 -0.1) trans sink series dangle))
  ((agent-trans-sink-series-dangle (0.1 0.6 0.1 0.1 -0.1) trans sink series dangle))
  ((agent-trans-sink-series-dangle (0.1 0.1 0.6 0.1 -0.1) trans sink series dangle))
  ((agent-rotat-sink-series-dangle (0.2 0.2 0.2 0.2 -0.2) rotat sink series dangle))
  ((agent-rotat-sink-series-dangle (0.6 0.1 0.1 0.1 -0.1) rotat sink series dangle))
  ((agent-rotat-sink-series-dangle (0.1 0.6 0.1 0.1 -0.1) rotat sink series dangle))
  ((agent-rotat-sink-series-dangle (0.1 0.1 0.6 0.1 -0.1) rotat sink series dangle))
  ((agent-elect-sink-series-dangle (0.2 0.2 0.2 0.2 -0.2) elect sink series dangle))
  ((agent-elect-sink-series-dangle (0.6 0.1 0.1 0.1 -0.1) elect sink series dangle))
  ((agent-elect-sink-series-dangle (0.1 0.6 0.1 0.1 -0.1) elect sink series dangle))
  ((agent-elect-sink-series-dangle (0.1 0.1 0.6 0.1 -0.1) elect sink series dangle))
  ((agent-hydra-sink-series-dangle (0.2 0.2 0.2 0.2 -0.2) hydra sink series dangle))
  ((agent-hydra-sink-series-dangle (0.6 0.1 0.1 0.1 -0.1) hydra sink series dangle))
  ((agent-hydra-sink-series-dangle (0.1 0.6 0.1 0.1 -0.1) hydra sink series dangle))
  ((agent-hydra-sink-series-dangle (0.1 0.1 0.6 0.1 -0.1) hydra sink series dangle))
  ((agent-trans-source-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) trans source parallel dangle))
  ((agent-trans-source-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) trans source parallel dangle))
  ((agent-trans-source-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) trans source parallel dangle))
  ((agent-trans-source-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) trans source parallel dangle))
  ((agent-rotat-source-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) rotat source parallel dangle))
  ((agent-rotat-source-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) rotat source parallel dangle))
  ((agent-rotat-source-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) rotat source parallel dangle))
  ((agent-rotat-source-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) rotat source parallel dangle))
  ((agent-elect-source-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) elect source parallel dangle))
  ((agent-elect-source-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) elect source parallel dangle))
  ((agent-elect-source-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) elect source parallel dangle))
  ((agent-elect-source-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) elect source parallel dangle))
  ((agent-hydra-source-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) hydra source parallel dangle))
  ((agent-hydra-source-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) hydra source parallel dangle))
  ((agent-hydra-source-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) hydra source parallel dangle))
  ((agent-hydra-source-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) hydra source parallel dangle))
  ((agent-trans-sink-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) trans sink parallel dangle))
  ((agent-trans-sink-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) trans sink parallel dangle))
  ((agent-trans-sink-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) trans sink parallel dangle))
  ((agent-trans-sink-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) trans sink parallel dangle))
  ((agent-rotat-sink-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) rotat sink parallel dangle))
  ((agent-rotat-sink-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) rotat sink parallel dangle))
  ((agent-rotat-sink-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) rotat sink parallel dangle))
  ((agent-rotat-sink-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) rotat sink parallel dangle))
  ((agent-elect-sink-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) elect sink parallel dangle))
  ((agent-elect-sink-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) elect sink parallel dangle))
  ((agent-elect-sink-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) elect sink parallel dangle))
  ((agent-elect-sink-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) elect sink parallel dangle))
  ((agent-hydra-sink-parallel-dangle (0.2 0.2 0.2 0.2 -0.2) hydra sink parallel dangle))
  ((agent-hydra-sink-parallel-dangle (0.6 0.1 0.1 0.1 -0.1) hydra sink parallel dangle))
  ((agent-hydra-sink-parallel-dangle (0.1 0.6 0.1 0.1 -0.1) hydra sink parallel dangle))
  ((agent-hydra-sink-parallel-dangle (0.1 0.1 0.6 0.1 -0.1) hydra sink parallel dangle))
  )
 
;;; INSTANTIATION-AGENTS
 ((agent-cheap-upper-mg-most-used-datum)
  (agent-cheap-middle-mg-most-used-datum)
  (agent-cheap-lower-mg-most-used-datum)
  (agent-light-upper-mg-most-used-datum)
  (agent-light-middle-mg-most-used-datum)
  (agent-light-lower-mg-most-used-datum)
  (agent-efficient-upper-mg-most-used-datum)
  (agent-efficient-middle-mg-most-used-datum)
  (agent-efficient-lower-mg-most-used-datum)
  (agent-cheap-upper-mg-least-used-datum)
  (agent-cheap-middle-mg-least-used-datum)
  (agent-cheap-lower-mg-least-used-datum)
  (agent-light-upper-mg-least-used-datum)
  (agent-light-middle-mg-least-used-datum)
  (agent-light-lower-mg-least-used-datum)
  (agent-efficient-upper-mg-least-used-datum)
  (agent-efficient-middle-mg-least-used-datum)
  (agent-efficient-lower-mg-least-used-datum))
 
;;; FRAGMENT-AGENTS
 ((agent-cheap-cheaper-in-comps)
  (agent-expensive-cheaper-in-comps)
  (agent-light-lighter-in-comps)
  (agent-heavy-lighter-in-comps)
  (agent-cheap-doubles-in-comps)
  (agent-expensive-doubles-in-comps)
  (agent-light-doubles-in-comps)
  (agent-heavy-doubles-in-comps)
  (agent-cheap-dangles-in-graph)
  (agent-expensive-dangles-in-graph)
  (agent-light-dangles-in-graph)
  (agent-heavy-dangles-in-graph)
  (agent-cheap-cheaper-in-graph)
  (agent-expensive-cheaper-in-graph)
  (agent-light-lighter-in-graph)
  (agent-heavy-lighter-in-graph)
  (agent-cheap-doubles-in-graph)
  (agent-expensive-doubles-in-graph)
  (agent-light-doubles-in-graph)
  (agent-heavy-doubles-in-graph))

;;; TREND-AGENTS
 (t-agent-group-c-agents 
  t-agent-group-i-agents 
  ;;t-agent-group-f-agents 
  t-agent-group-components 
  t-agent-group-embodiments 
  ;;t-agent-graph-embodiments)
)
 )
